import type { Theme } from '../types';

export const themes: Theme[] = [
  {
    id: 'apple-notes',
    name: 'Apple Notes',
    nameCn: '苹果备忘录',
    backgroundColor: '#ffffff',
    textColor: '#1d1d1f',
    headingColor: '#1d1d1f',
    codeBackground: '#f5f5f7',
    codeColor: '#e73c3c',
    borderLeftColor: '#007aff',
    cardBackground: '#ffffff',
    shadow: '0 4px 24px rgba(0, 0, 0, 0.08)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", sans-serif',
    borderRadius: '12px',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    nameCn: 'Instagram风格',
    backgroundColor: '#ffffff',
    textColor: '#262626',
    headingColor: '#262626',
    codeBackground: '#f5f5f5',
    codeColor: '#e1306c',
    borderLeftColor: '#833ab4',
    cardBackground: '#ffffff',
    shadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, sans-serif',
    borderRadius: '16px',
  },
  {
    id: 'notebook',
    name: 'Notebook',
    nameCn: '线圈笔记本',
    backgroundColor: '#fef9f3',
    textColor: '#333333',
    headingColor: '#2c3e50',
    codeBackground: '#f8f4e8',
    codeColor: '#c0392b',
    borderLeftColor: '#3498db',
    cardBackground: '#fef9f3',
    shadow: '0 4px 24px rgba(0, 0, 0, 0.1)',
    fontFamily: '"Georgia", "Times New Roman", serif',
    borderRadius: '8px',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    nameCn: '波普艺术',
    backgroundColor: '#fff200',
    textColor: '#000000',
    headingColor: '#ff00ff',
    codeBackground: '#00ffff',
    codeColor: '#000000',
    borderLeftColor: '#ff0000',
    cardBackground: '#fff200',
    shadow: '6px 6px 0 #000000',
    fontFamily: '"Arial Black", "Impact", sans-serif',
    borderRadius: '0',
  },
  {
    id: 'bytedance',
    name: 'ByteDance',
    nameCn: '字节范',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#1f2329',
    codeBackground: '#f5f6f7',
    codeColor: '#db4d39',
    borderLeftColor: '#3370ff',
    cardBackground: '#ffffff',
    shadow: '0 2px 12px rgba(0, 0, 0, 0.08)',
    fontFamily: '"SF Pro Text", -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif',
    borderRadius: '8px',
  },
  {
    id: 'alibaba',
    name: 'Alibaba',
    nameCn: '阿里橙',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#ff6a00',
    codeBackground: '#f6f8fa',
    codeColor: '#d63384',
    borderLeftColor: '#ff6a00',
    cardBackground: '#ffffff',
    shadow: '0 4px 16px rgba(255, 106, 0, 0.1)',
    fontFamily: '"PingFang SC", "Microsoft YaHei", -apple-system, sans-serif',
    borderRadius: '8px',
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    nameCn: '艺术装饰',
    backgroundColor: '#f5f0e8',
    textColor: '#2c2c2c',
    headingColor: '#b8860b',
    codeBackground: '#e8e0d0',
    codeColor: '#8b4513',
    borderLeftColor: '#b8860b',
    cardBackground: '#f5f0e8',
    shadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
    fontFamily: '"Playfair Display", "Georgia", serif',
    borderRadius: '4px',
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    nameCn: '玻璃拟态',
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textColor: '#ffffff',
    headingColor: '#ffffff',
    codeBackground: 'rgba(255, 255, 255, 0.2)',
    codeColor: '#ffffff',
    borderLeftColor: 'rgba(255, 255, 255, 0.5)',
    cardBackground: 'rgba(255, 255, 255, 0.25)',
    shadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
    fontFamily: '"SF Pro Display", -apple-system, BlinkMacSystemFont, sans-serif',
    borderRadius: '16px',
  },
  {
    id: 'warm',
    name: 'Warm',
    nameCn: '温暖柔和',
    backgroundColor: '#fdf6e3',
    textColor: '#5c5c5c',
    headingColor: '#cb4b16',
    codeBackground: '#eee8d5',
    codeColor: '#dc322f',
    borderLeftColor: '#cb4b16',
    cardBackground: '#fdf6e3',
    shadow: '0 4px 20px rgba(203, 75, 22, 0.1)',
    fontFamily: '"Palatino", "Book Antiqua", serif',
    borderRadius: '12px',
  },
  {
    id: 'minimal-gray',
    name: 'Minimal Gray',
    nameCn: '简约高级灰',
    backgroundColor: '#f8f9fa',
    textColor: '#495057',
    headingColor: '#212529',
    codeBackground: '#e9ecef',
    codeColor: '#d63384',
    borderLeftColor: '#6c757d',
    cardBackground: '#f8f9fa',
    shadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    borderRadius: '8px',
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    nameCn: '极简黑白',
    backgroundColor: '#ffffff',
    textColor: '#1a1a1a',
    headingColor: '#000000',
    codeBackground: '#f5f5f5',
    codeColor: '#333333',
    borderLeftColor: '#000000',
    cardBackground: '#ffffff',
    shadow: 'none',
    fontFamily: '"Helvetica Neue", Arial, sans-serif',
    borderRadius: '0',
  },
  {
    id: 'dreamy',
    name: 'Dreamy',
    nameCn: '梦幻渐变',
    backgroundColor: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    textColor: '#4a4a4a',
    headingColor: '#c850c0',
    codeBackground: 'rgba(255, 255, 255, 0.6)',
    codeColor: '#c850c0',
    borderLeftColor: '#c850c0',
    cardBackground: 'rgba(255, 255, 255, 0.4)',
    shadow: '0 8px 32px rgba(200, 80, 192, 0.2)',
    fontFamily: '"Quicksand", "Nunito", sans-serif',
    borderRadius: '20px',
  },
  {
    id: 'nature',
    name: 'Nature',
    nameCn: '清新自然',
    backgroundColor: '#f0f7f0',
    textColor: '#2d5a27',
    headingColor: '#1a7a1a',
    codeBackground: '#d4e8d4',
    codeColor: '#8b4513',
    borderLeftColor: '#228b22',
    cardBackground: '#f0f7f0',
    shadow: '0 4px 20px rgba(34, 139, 34, 0.1)',
    fontFamily: '"Nunito", "Segoe UI", sans-serif',
    borderRadius: '12px',
  },
  {
    id: 'xiaohongshu',
    name: 'Xiaohongshu',
    nameCn: '小红书',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#ff2442',
    codeBackground: '#f5f5f5',
    codeColor: '#ff2442',
    borderLeftColor: '#ff2442',
    cardBackground: '#ffffff',
    shadow: '0 4px 20px rgba(255, 36, 66, 0.1)',
    fontFamily: '"PingFang SC", "Microsoft YaHei", sans-serif',
    borderRadius: '12px',
  },
  {
    id: 'notebook-ruled',
    name: 'Notebook Ruled',
    nameCn: '笔记本',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#2c3e50',
    codeBackground: '#f8f9fa',
    codeColor: '#e74c3c',
    borderLeftColor: '#3498db',
    cardBackground: '#ffffff',
    shadow: '0 4px 16px rgba(0, 0, 0, 0.1)',
    fontFamily: '"Courier New", monospace',
    borderRadius: '4px',
  },
  {
    id: 'business',
    name: 'Business',
    nameCn: '商务简报',
    backgroundColor: '#ffffff',
    textColor: '#333333',
    headingColor: '#1a365d',
    codeBackground: '#f7fafc',
    codeColor: '#e53e3e',
    borderLeftColor: '#2b6cb0',
    cardBackground: '#ffffff',
    shadow: '0 4px 24px rgba(26, 54, 93, 0.1)',
    fontFamily: '"Segoe UI", "Helvetica Neue", sans-serif',
    borderRadius: '8px',
  },
  {
    id: 'japanese',
    name: 'Japanese',
    nameCn: '日本杂志',
    backgroundColor: '#faf8f5',
    textColor: '#333333',
    headingColor: '#c41e3a',
    codeBackground: '#f0ede8',
    codeColor: '#c41e3a',
    borderLeftColor: '#c41e3a',
    cardBackground: '#faf8f5',
    shadow: '0 4px 20px rgba(196, 30, 58, 0.08)',
    fontFamily: '"Noto Sans JP", "Hiragino Sans", sans-serif',
    borderRadius: '4px',
  },
  {
    id: 'darktech',
    name: 'Dark Tech',
    nameCn: '暗黑科技',
    backgroundColor: '#0d1117',
    textColor: '#c9d1d9',
    headingColor: '#58a6ff',
    codeBackground: '#161b22',
    codeColor: '#79c0ff',
    borderLeftColor: '#58a6ff',
    cardBackground: '#161b22',
    shadow: '0 4px 24px rgba(88, 166, 255, 0.15)',
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    borderRadius: '8px',
  },
  {
    id: 'typewriter',
    name: 'Typewriter',
    nameCn: '复古打字机',
    backgroundColor: '#f4f1ea',
    textColor: '#2c2c2c',
    headingColor: '#1a1a1a',
    codeBackground: '#e8e4db',
    codeColor: '#8b0000',
    borderLeftColor: '#8b0000',
    cardBackground: '#f4f1ea',
    shadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
    fontFamily: '"Courier New", "American Typewriter", monospace',
    borderRadius: '4px',
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    nameCn: '水彩艺术',
    backgroundColor: 'linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)',
    textColor: '#37474f',
    headingColor: '#00838f',
    codeBackground: 'rgba(255, 255, 255, 0.7)',
    codeColor: '#00838f',
    borderLeftColor: '#00bcd4',
    cardBackground: 'rgba(255, 255, 255, 0.5)',
    shadow: '0 4px 24px rgba(0, 188, 212, 0.15)',
    fontFamily: '"Palatino", "Georgia", serif',
    borderRadius: '16px',
  },
  {
    id: 'traditional-chinese',
    name: 'Traditional Chinese',
    nameCn: '中国传统',
    backgroundColor: '#fdf8f0',
    textColor: '#333333',
    headingColor: '#c41e3a',
    codeBackground: '#f5f0e5',
    codeColor: '#8b0000',
    borderLeftColor: '#c41e3a',
    cardBackground: '#fdf8f0',
    shadow: '0 4px 20px rgba(196, 30, 58, 0.1)',
    fontFamily: '"SimSun", "STSong", serif',
    borderRadius: '4px',
  },
  {
    id: 'fairytale',
    name: 'Fairytale',
    nameCn: '儿童童话',
    backgroundColor: '#fff5f5',
    textColor: '#4a4a4a',
    headingColor: '#f56565',
    codeBackground: '#fed7d7',
    codeColor: '#c53030',
    borderLeftColor: '#fc8181',
    cardBackground: '#fff5f5',
    shadow: '0 8px 32px rgba(252, 129, 129, 0.2)',
    fontFamily: '"Comic Sans MS", "Chalkboard SE", cursive',
    borderRadius: '20px',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    nameCn: '赛博朋克',
    backgroundColor: '#0a0a0a',
    textColor: '#00ff00',
    headingColor: '#ff00ff',
    codeBackground: '#1a1a2e',
    codeColor: '#00ffff',
    borderLeftColor: '#ff00ff',
    cardBackground: '#1a1a2e',
    shadow: '0 0 30px rgba(255, 0, 255, 0.3)',
    fontFamily: '"Share Tech Mono", "VT323", monospace',
    borderRadius: '0',
  },
  {
    id: 'meadow',
    name: 'Meadow Dawn',
    nameCn: '青野晨光',
    backgroundColor: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
    textColor: '#333333',
    headingColor: '#2d5a27',
    codeBackground: 'rgba(255, 255, 255, 0.7)',
    codeColor: '#2d5a27',
    borderLeftColor: '#228b22',
    cardBackground: 'rgba(255, 255, 255, 0.5)',
    shadow: '0 8px 32px rgba(34, 139, 34, 0.15)',
    fontFamily: '"Nunito", "Lato", sans-serif',
    borderRadius: '16px',
  },
];

export const getThemeById = (id: string): Theme | undefined => {
  return themes.find((theme) => theme.id === id);
};
